[package]
name = "rc-core"
version = "0.1.0"
edition = "2021"
authors = ["rc-ss"]

[lib]
path = "src/lib.rs"

[dependencies]
defmt = { workspace = true }
bitflags = { workspace = true }
esp-hal = { workspace = true }
esp-radio = { workspace = true }
embassy-futures = { workspace = true }

