name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rust-src
          target: riscv32imac-unknown-none-elf
          override: true
      - name: Cargo check
        run: cargo check --target riscv32imac-unknown-none-elf
